# Generated by Django 2.2 on 2021-11-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0007_auto_20211109_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='question',
            new_name='Tweet',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='user',
        ),
    ]
