# Generated by Django 2.2 on 2021-11-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_choice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Like',
        ),
    ]
