# Generated by Django 3.2.8 on 2021-11-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0016_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
